// <auto-generated />
namespace services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class reset : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reset));
        
        string IMigrationMetadata.Id
        {
<<<<<<< HEAD:services/Migrations/201911041620253_reset.Designer.cs
            get { return "201911041620253_reset"; }
=======
            get { return "201910292247034_reset"; }
>>>>>>> test:services/Migrations/201910292247034_reset.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
