// <auto-generated />
namespace services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class new_production_fields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_production_fields));
        
        string IMigrationMetadata.Id
        {
            get { return "201905241625571_new_production_fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
